---
title: "Environmental Data Science Lab - Highlights"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
```

### **Welcome** {data-commentary-width=400; #welcome}

```{r}
print("frame-1")
```

*** 

Ahoy Mateys!

```{r}
library(tidyverse)
library(leaflet)
library(mapview)
library(mapedit)
library(sf)
library(here)
library(glue)
library(fs)
library(vembedr)
library(bsplus)
source(here("functions.R"))

#file.exists(here("docs/modal/siting_framework.md"))
modal_parts <- function(id, size = "large"){
  title = str_replace_all(id, "_", " ") %>% str_to_title()
  path = here(glue("docs/modal/{id}.md"))
  
  if (!file.exists(path)) stop(glue("{md}: {path} does not exist!"))

  list(id=id, title=title, path=path)
}
m <- modal_parts("siting_framework")
bs_modal(id=m$id, title=m$title, size=m$size, body = includeMarkdown(m$path))
bs_button(m$title, button_type = "primary") %>% bs_attach_modal(m$id)
#}
#globalenv()
#btn_modal("siting_framework")
```

Welcome to a reel of research highlights for Dr. Ben Best.

https://vimeo.com/

### Frame 2 {data-commentary-width=400; #frame2}

```{r}
print("frame-2")
```

*** 

Some commentary about Frame 2.

### Frame 3  {#frame3}

```{r}
print("frame-3")
```

*** 

Some commentary about Frame 3. 



